# Generated by Django 5.0.5 on 2024-05-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liveconfigs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configrow",
            options={
                "verbose_name": "Конфигурация",
                "verbose_name_plural": "Конфигурации",
            },
        ),
    ]
